apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-server
        resources: {}
        image: ahmetgrbzz/helloworld-app:v1
        env:
        - name: ELASTICSEARCH_URL
          value: "http://e-service.default.svc.cluster.local:9200"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: h-secret
              key: ELASTICSEARCH_PASSWORD
        

        # envFrom:
        # - secretRef:
        #     name: hello-app-secret
        # - configMapRef:
        #     name: hello-app-config    
        ports:
        - containerPort: 8081
          hostPort: 80
