name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Kodunuzu Checkout Etmek
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Mevcut Versiyonu Kontrol Et ve Yeni Versiyon Belirle
      - name: Get latest version tag from Docker Hub
        id: versioning
        run: |
          # Docker Hub'dan mevcut etiketleri çek
          tags=$(curl -s -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
            https://hub.docker.com/v2/repositories/ahmetgrbzz/helloworld-app/tags | \
            jq -r '.results[].name')

          echo "Fetched tags: $tags"

          # Eğer mevcut bir etiket yoksa v1 başlat
          if [ -z "$tags" ]; then
            new_version="v1.00"
          else
            # En son versiyonu bul ve artır
            latest_version=$(echo "$tags" | grep -E '^v[0-9]+(\.[0-9]+)?$' | sort -V | tail -n 1)
            if [ -z "$latest_version" ]; then
              new_version="v1.00"
            else
              new_version=$(echo $latest_version | awk -F. '{printf "v%d.%02d\n", $1, ($2+1)}')
            fi
          fi

          echo "Latest version: $latest_version"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_ENV

      # Docker Build ve Push
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ahmetgrbzz/helloworld-app:${{ env.new_version }}
