name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Kodunuzu Checkout Etmek
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Build ve Push
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ahmetgrbzz/helloworld-app:latest
